services: 
  auth-db:
    image: mysql:8.0
    container_name: chatapp-auth-db
    environment:
      - MYSQL_DATABASE: ${AUTH_DB_NAME:-chatapp_auth_service}
        MYSQL_USER: ${AUTH_DB_USER:-chatapp_auth_user}
        MYSQL_ROOT_PASSWORD: ${AUTH_DB_PASSWORD:-chatapp_auth_password}
    command: ["mysqld", "--default"]