@baseGateway = http://localhost:4007


### Auth Register
POST {{baseGateway}}/auth/register
content-type: application/json

{
    "email": "janedoe@example.com",
    "displayName": "Jane Doe",
    "password": "Password123!"
}


### Auth Login
POST {{baseGateway}}/auth/login
content-type: application/json

{
    "email": "nancyasiuloka@example.com",
    "password": "Password123!"
}