@baseGateway = http://localhost:4004


### Auth Register
POST {{baseGateway}}/auth/register
content-type: application/json

{
    "email": "nancyasiuloka@example.com",
    "displayName": "Nancy Asiuloka",
    "password": "Password123!"
}


### Auth Login
POST {{baseGateway}}/auth/login
content-type: application/json

{
    "email": "nancyasiuloka@example.com",
    "password": "Password123!"
}